version: '3'
services:
  hs-backend:
    container_name: hs-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone
    external_links:
      - hs-mysql:db #可以用db这个域名访问mysql服务
      - hs-redis:redis #可以用redis这个域名访问redis服务
    networks:
      - hs_net

networks:
  hs_net:
    external: true