# 连接远程db环境配置

server:
  port: 8081

# Spring配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据源配置
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://116.62.205.26:3307/health_station?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 666888

  # redis 配置
  redis:
    # 地址
    host: 116.62.205.26
    # 端口，默认为6379
    port: 6380

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false